---
dependency:
  name: galaxy
lint: |
  yamllint -d "{ignore: .venv}" .
  ansible-lint defaults files meta molecule tasks
  flake8 molecule
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1604-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
scenario:
  name: default
verifier:
  name: testinfra
